### ISSUE TITLE
Unable to Sign Up due to `id` non-null constraint violated

### ISSUE THREAD

**Issue by TechieBlossom** [ibhavikmakwana/supabase_playground#18]
**Describe the bug**
After successful installation of app and creation of database, unable to Sign Up due to `id` non-null constraint violated.

**To Reproduce**
1. Go to 'Sign Up' tab
2. Fill details - email, password and confirm password 
3. Click SignUp button
4. See error in terminal

**Expected behavior**
A row must be created with newly registered profile

**Screenshots**
<img width="1611" alt="Screenshot 2021-07-25 at 2 13 32 PM" src="https://user-images.githubusercontent.com/39679158/126893189-61d7f4e7-aa08-40e2-ba14-9348de4235c0.png">

**Smartphone (please complete the following information):**
 - Device: iPhone12 Simulator
 - OS: iOS 14.4

**Additional context**
Profile table is created in Supabase

**Comment by ibhavikmakwana** [comment]
Hey sorry for the delayed response, can you share you table?
also I have  Update README.md with proper query.

**Comment by TechieBlossom** [comment]
Here it the table structure, with latest readme. @ibhavikmakwana 

<img width="1718" alt="Screenshot 2021-07-31 at 10 52 55 AM" src="https://user-images.githubusercontent.com/39679158/127729663-4ac69c15-ee7d-48e7-82d0-7d57586240c9.png">

**Comment by ibhavikmakwana** [comment]
Can you take the latest code now, try doing sign up again?
I think it will work now, I have update code as well.

**Comment by TechieBlossom** [comment]
Just took latest. 10 mints back.

**Comment by ibhavikmakwana** [comment]
Can you see if the user authentication is happening in the Supa Base?

Goto `Authentication` => `User`


Also can you check the `Settings` and make sure `Disable email confirmations` green which is active.

<img width="771" alt="Screenshot 2021-07-31 at 11 05 09 AM" src="https://user-images.githubusercontent.com/22465800/127729933-3a259467-e03a-4f52-8408-bde87ef013ab.png">

If that's an issue looks like I have to update read me again, as I am not verifying email addresses right now.

**Comment by TechieBlossom** [comment]
Yes, disable email confirmations was unchecked. I have made it checked now.
I can see my user waiting for verification. I deleted the user and retried signup. This time, I can successfully sign up and see my user in Supa Base.

Thanks.

**Comment by ibhavikmakwana** [comment]
Great, I'll update the Read Me with appropriate screen shot.
Thanks for reporting this, closing this now.
