### ISSUE TITLE
Add launcher app icons and splash screen UI with icon.

### ISSUE THREAD

**Issue by ibhavikmakwana** [ibhavikmakwana/supabase_playground#6]

**Comment by adityathakurxd** [comment]
Can I take up this issue?

**Comment by ibhavikmakwana** [comment]
Yes Sure @adityathakurxd

**Comment by adityathakurxd** [comment]
I was getting an error while setting up the project locally.
```
Error when reading 'lib/main.reflectable.dart': The system cannot find the file specified.
```
This is the same in all files that have `part '  '`.
I looked it up on Google and couldn't find a solution.

![supabase_playground – dashboard_store dart 7_22_2021 7_54_31 PM](https://user-images.githubusercontent.com/53579386/126656395-c5a2082a-26a7-478d-b85e-b00f9c2e4ec1.png)

Could you guide me on how to resolve this?

**Comment by ibhavikmakwana** [comment]
Run this command to generate the code.

`flutter pub run build_runner build`
