### ISSUE TITLE
Unable to Sign up while running on simulator

### ISSUE THREAD

**Issue by deepu** [ibhavikmakwana/supabase_playground#9]
**Describe the bug**
Running debug build on simulator, I can see the main screen. 
I get this error "flutter: Error: {data: null, status: 403, error: {message: new row violates row-level security policy for table "profiles", details: null, hint: null, code: 42501}, count: null}"  when I click on Signup after filling in email, password .

**To Reproduce**
1. Download repo to local
2. Implement everything on Read me (connecting to supabase, build run)
3. Run the app on the Simulator. 
4. Go to Sign Up
5. Fill email, password, confirm password 
6. Click Signup button

**Expected behavior**
Sign up should complete and proceed to the next screen. 
Instead it gets stuck on this screen and I see an error message in the console. 
```
flutter: Error: {data: null, status: 403, error: {message: new row violates row-level security policy for table "profiles", details: null, hint: null, code: 42501}, count: null}
```
**Screenshots**
The screen where error is showing up.
<img width="435" alt="Screenshot 2021-07-22 at 6 31 27 PM" src="https://user-images.githubusercontent.com/55172/126643128-d0e5ab0b-ac56-4459-9177-425be3c3398c.png">

**Smartphone (please complete the following information):**
 Simulator - iPhone 12 Pro Max

**Comment by ibhavikmakwana** [comment]
Can you try deleting your table and running query again but this time without row level security?

i.e. Do not write below line

`alter table profiles enable row level security;`

I might have missed something.

**Comment by ibhavikmakwana** [comment]
I don't have exact idea that if I have added the row level security or not, have to check.

**Comment by ibhavikmakwana** [comment]
Update README.md with proper query, can you try creating table once again with that query?

**Comment by ibhavikmakwana** [comment]
Closing this issue as I have updated README.md with latest Query to Create Table(s), Feel free to open it again if still stuck with issue.

**Comment by deepu** [comment]
Sorry I was just busy last few days so couldn't test this. 

Tested now according to latest instructions on Readme. 
All working fine now.

**Comment by ibhavikmakwana** [comment]
Great, Thanks!
